### ISSUE TITLE
Error: 'stack' could not be spawned...

### ISSUE THREAD

**Issue by eatobin** [atom-haskell/ide-haskell-cabal#18]
When trying to clean or build a project in atom I receive the attached error. This is new and I wonder if it is associated with the recent update of stack to ver 1.6.1?

![builder](https://user-images.githubusercontent.com/870698/33799146-360a37fe-dceb-11e7-925b-bb2825abc08f.png)

This error is occurring on my Linux Manjaro machine and is NOT happening on my Mac with same config.

I can also confirm that stack is on my path:

    eric@linux-epth:~$ which stack
    /home/eric/.local/bin/stack
    eric@linux-epth:~$

Thank you for your help with this.

**Comment by lierdakil** [comment]
Well, no luck reproducing with `Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0` on Gentoo Linux, so probably a configuration error? Try running Atom from terminal, maybe your interactive shell has different environment (f.ex. because you set up `PATH` in `.bashrc` -- which you shouldn't, in general, do, there's `.bash_profile` to do that)

**Comment by eatobin** [comment]
You were right - a config issue. Thank you!
