### ISSUE TITLE
List of build targets empty?

### ISSUE THREAD

**Issue by edsko** [atom-haskell/ide-haskell-cabal#19]
The list of build targets just lists "Auto", but running 'new-build' shows that actually it did correctly parse the `.cabal` file, figure out which components are there, and actually it even somehow magically picked the _right_ component too.. :)

**Comment by lierdakil** [comment]
I can't reproduce on my end, all build targets show up as expected pretty much. So probably need more detail.

**Comment by lierdakil** [comment]
So... any news on this? I might have an idea why this might be...

See, target selection operates on the level of atom's project directories (what `atom.project.getPaths()` returns pretty much), because traversing the whole sub-tree of every project directory in search of a cabalfile isn't something we really want to do (for one, it might take *ages* -- and we can't even be sure we *will* find any or if those will even be relevant to the project at hand).

The reverse (traversing all *parents*) is actually pretty simple, so `Auto: Auto` target traverses all parent directories of the currently-active text editor in search of a cabalfile, and then assigns target based on current text editor's path as well.

So... for manual target selection to work, you need to have your cabalfile in the project root pretty much.

**Comment by edsko** [comment]
I'm not sure I follow you here. My setup looks something like this

```
~/clients/project_root   # atom started from command line here
~/clients/project_root/cabal.project # is read by `cabal new-build` to figure out project context
~/clients/project_root/some_library  # library with some test suits I'm actually working on
~/clients/project_root/some_library/library.cabal  # cabal file for that library
~/clients/project_root/some_library/test/A/M.hs # some module in a test-suite of that library I'm editing
```

When I run build, it actually selects the right target (the name of the test suite of `some_library` that `M.hs` happens to belong to), but when I ask for a list of targets, I get only 'Auto'.

I don't know if this matches your hypothesis or not?

**Comment by lierdakil** [comment]
Well, since the package isn't aware of `cabal.project` files, it's pretty much the same as having

```
~/clients/project_root   # atom looks for cabal file to parse for list of targets here
~/clients/project_root/some_library/library.cabal  # cabal file it should actually parse
```

Which, yeah, matches my hypothesis pretty well.

Opening `~/clients/project_root/some_library` in Atom should work as you would expect (pretty sure `cabal new-build` doesn't really care if it's run in a child directory, as long it can find `cabal.project` up the hierarchy, although I don't use it personally, so might be entirely wrong)

I think we could actually parse `cabal.project`, but I'm not sure when I find time to actually take a close look at it. At the very least, it seems actual Cabal code for handling new-build stuff is [hidden in the bowels of cabal-install](https://github.com/haskell/cabal/blob/2.0/cabal-install/Distribution/Client/ProjectConfig.hs) so there likely won't be an easy way to leverage that via hs to js compilation, as we did with cabal file parsing. And even if we just parse `packages` field, it's going to be somewhat tricky to replicate Cabal's behaviour...

**Comment by edsko** [comment]
No, I think parsing `cabal.project` is not a path we want to go down :) I'm still confused though. How is it able to find the right target (it calls cabal-new with the correct name for the component that `M.hs` happens to belong to) but yet not able to show me a list of targets? Sorry for being a bit slow on the uptake here :)

**Comment by lierdakil** [comment]
`Auto: Auto` uses a somewhat smarter algorithm, based on the path of your currently active text editor. So let's imagine you have `~/clients/project_root/some_library/test/A/M.hs` currently open. Then Atom will look for cabal file this Haskell source relates to in all parent directories iteratively, i.e. `~/clients/project_root/some_library/test/A/`, `~/clients/project_root/some_library/test/`, `~/clients/project_root/some_library/` -- at which point it finds `~/clients/project_root/some_library/library.cabal`, parses it, and happily assigns a `test` component based on the relative path `test/A/M.hs`

As for why it doesn't do something similar to look for *all* available targets, I would hope that should be rather obvious: searching *up* the filesystem hierarchy has linear complexity while searching *down* has worst-case exponential, and in the presence of junctions or symlinks doesn't even terminate at all necessarily without some unsightly hacks. So finding *all* possible projects/targets is out of the question -- it's slow and a major headache. And showing targets based on currently-open text editor is... well, not very intuitive and can lead to apparent lack of reproducibility, so the choice is in favour of simpler, if less powerful, behaviour.

Pretty much boils down to this distinction: when you run `build` with an open text editor, you are reasonable to expect that currently-open file will be built, and it's easy to figure out what project/target a given file belongs to. But if you want to select a target manually, there's a good chance you'd like to see all possible targets for all projects in scope -- which is very tricky to get in the general case. Hence, instead of a general case, for the purpose of searching for available projects, the package assumes that 'Atom project directory' ≡ 'Cabal package directory'

Sorry if it doesn't seem to make a lot of sense, I'm a bit sleep-deprived, so it's possible that a simpler explanation eludes me.

**Comment by edsko** [comment]
> And showing targets based on currently-open text editor is... well, not very intuitive and can lead to apparent lack of reproducibility, so the choice is in favour of simpler, if less powerful, behaviour.

Aha, _that's_ the key difference then. Ok, that makes sense. Perhaps when cabal new-build actually gets to a mature release we can rethink this and cabal.project stuff. Thanks! :)
