### ISSUE TITLE
cabal couldn`t be found

### ISSUE THREAD

**Issue by wapxmas** [atom-haskell/ide-haskell-cabal#8]
On Windows:
'cabal' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

cabal is in path, successfully run from console.

**Comment by lierdakil** [comment]
Check your path in Atom by running `process.env.PATH` in Atom's console (View → Developer →  Toggle Developer Tools).
You also might solve this issue by writing correct PATH in package settings.

**Comment by wapxmas** [comment]
SOLVED! The problem was that the PATH, a variable in Windows designated as Path but Atom tries to find it as PATH (only uppercase), so i tried to rename Path in Windows environment to PATH and no luck, then i just wrote in the init.coffee:

`process.env.PATH = process.env.Path`

So it works!

**Comment by lierdakil** [comment]
Actually, on Windows there are several different capitalizations of path, which all mean different things -_-

Direct substitution might not be the best strategy.

This issue is probably due to recent changes in Atom core w.r.t. PATH handling.

I think this issue should be fixed by v1.2.2. Please do remove that hack from `init.coffee`, it may lead to hard-to-pinpoint issues in the future.

**Comment by wapxmas** [comment]
@lierdakil Thanks!
